name: Generate Contribution Animations

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate animations
        uses: Platane/snk@v3
        with:
          github_user_name: tausif-islam-sheik
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/pacman.svg?palette=github-dark

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
